#!/usr/bin/env python3
"""Make sure we get the right config source.

PYTHON_ARGCOMPLETE_OK
"""
from milc import cli


@cli.argument('-n', '--name', help='Name to greet', default='World')
@cli.entrypoint('Greet a user.')
def main(cli):
    cli.echo('Hello, %s, from %s!', cli.config.general.name, cli.config_source.general.name)


if __name__ == '__main__':
    cli()
