#!/usr/bin/env python3
"""Hello World implementation using MILC.

PYTHON_ARGCOMPLETE_OK
"""
from milc import cli


@cli.argument('-c', '--comma', arg_only=True, help='comma in output', default=True, action='store_boolean')
@cli.argument('-n', '--name', help='Name to greet', default='World')
@cli.entrypoint('Greet a user.')
def main(cli):
    comma = ',' if cli.args.comma else ''
    cli.log.debug('You used -v you lucky person!')
    cli.log.info('Hello%s %s, from cli.log.info!', comma, cli.config.general.name)
    cli.echo('{fg_red}Hello%s %s, from cli.echo!', comma, cli.config.general.name)


if __name__ == '__main__':
    cli()
