#!/usr/bin/env python3
"""Given two passwords make sure they match.

PYTHON_ARGCOMPLETE_OK
"""
from milc import cli
from milc.questions import password


@cli.entrypoint('Check that two passwords match.')
def main(cli):
    pw = password(confirm=True, confirm_limit=1)
    if pw is None:
        return 1

    return 0


if __name__ == '__main__':
    exit(cli())
