#!/usr/bin/env python3
"""Test and show off the spinner methods.

PYTHON_ARGCOMPLETE_OK
"""
from time import sleep

from milc import set_metadata

set_metadata(name='spinner_qmk', author='MILC', version='1.9.0')

from milc import cli


@cli.entrypoint('Show off spinners.')
def main(cli):
    my_spinner = {
        'interval': 100,
        'frames': [
            'Ψ     ψ',
            ' Ψ   ψ ',
            '  Ψ ψ  ',
            '   ψ   ',
            '  ψ Ψ  ',
            ' ψ   Ψ ',
            'ψ     Ψ',
            'Ψ     ψ',
            ' Ψ   ψ ',
            '  Ψ ψ  ',
            '   ψ   ',
            '  ψ Ψ  ',
            ' ψ   Ψ ',
            'ψ     Ψ',
        ]
    }

    cli.add_spinner('my_spinner', my_spinner)

    with cli.spinner(text='QMK Spinner!', spinner=my_spinner):
        sleep(10)


if __name__ == '__main__':
    cli()
